### ISSUE TITLE
AppDelegate.m - No visible @interface for 'UIView' declares the selector 'stringByEvaluatingJavaScriptFromString:'

### ISSUE THREAD

**Issue by ImranHParkResorts** [EddyVerbruggen/cordova-plugin-3dtouch#8] opened 2016-02-22 12:51 UTC
Hello there,

 I updated my ios app to cordova 6.0 and now I'm getting the above error and I am not able to find a fix for it.  My Xcode version is 7.2.1.

Any help is much appreciated.

Many Thanks
Imran

**Comment by EddyVerbruggen** [comment] 2016-02-22 15:02
Dupe of #7

**Closed by EddyVerbruggen** 2016-02-22 15:02 UTC

**Comment by ImranHParkResorts** [comment] 2016-02-22 15:30
Hi Eddy,

 I'm slightly confused as the fix you have for #7 talks about adding 3dtouch plugin and #8 talks about carnival plugin and in my app I don't have any of these. Do I need to install 3dtouch plugin as a fox for this issue?

Any help is much appreciated

Many Thanks

**Comment by EddyVerbruggen** [comment] 2016-02-22 15:37
In #7 I fixed the issue, #8 is this issue.

Are you aware you're in the 3D Touch plugin repo?
